# Generated by Django 5.0.8 on 2026-07-14 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('BLOG', 'Blog'), ('TESTIMONIAL', 'Testimonial'), ('PORTFOLIO', 'Portfolio'), ('SERVICE', 'Service'), ('CORE_PAGE', 'Core Page')], max_length=20)),
                ('content_id', models.IntegerField()),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], max_length=20)),
                ('content_snapshot', models.JSONField()),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, help_text='Reason for the change')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Content Version',
                'verbose_name_plural': 'Content Versions',
                'ordering': ['-changed_at'],
            },
        ),
    ]
