# Generated by Django 6.0.6 on 2026-07-11 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(default='Technician', max_length=100),
        ),
        migrations.CreateModel(
            name='ModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('module', models.CharField(choices=[('dashboard', 'Dashboard'), ('leads', 'Leads'), ('crm', 'CRM'), ('quotations', 'Quotations'), ('projects', 'Projects'), ('tenders', 'Tenders'), ('inventory', 'Inventory'), ('employees', 'Employees'), ('users', 'Users'), ('reports', 'Reports'), ('settings', 'Settings')], max_length=50)),
                ('permission', models.CharField(choices=[('view', 'View Only'), ('edit', 'View & Edit'), ('full', 'Full Access'), ('none', 'No Access')], default='none', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Module Permission',
                'verbose_name_plural': 'Module Permissions',
                'db_table': 'module_permissions',
                'unique_together': {('role', 'module')},
            },
        ),
    ]
