# Generated by Django 6.0.7 on 2026-09-06 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0027_rename_employees_p_employ_8f5c8b_idx_employees_p_employe_15bd24_idx_and_more'),
        ('users', '0006_userprofile_account_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='employees.department'),
        ),
    ]
