# Generated by Django 6.0.7 on 2026-09-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userprofile_department'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='modulepermission',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='modulepermission',
            name='job_title',
            field=models.CharField(blank=True, help_text='Optional job title override for specific roles', max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='modulepermission',
            unique_together={('role', 'module', 'job_title')},
        ),
    ]
