# Generated by Django 6.0.7 on 2026-09-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_modulepermission_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='job_title',
            field=models.CharField(blank=True, help_text="User's job title for permission overrides", max_length=100, null=True),
        ),
    ]
