# Generated by Django 6.0.7 on 2026-07-30 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0015_department_description_alter_employee_status'),
        ('projects', '0002_projectassignment'),
        ('users', '0005_invitation_permissions_userprofile_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRoleAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_role', models.CharField(help_text='Role assigned to this employee on the project', max_length=100)),
                ('is_team_lead', models.BooleanField(default=False, help_text='Whether this employee is the project clerk of works')),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.userprofile')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_allocations', to='employees.employee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_allocations', to='projects.project')),
            ],
            options={
                'ordering': ['-assigned_date'],
                'unique_together': {('employee', 'project', 'is_active')},
            },
        ),
    ]
