# Generated by Django 6.0.7 on 2026-07-30 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0016_department_department_head_department_description_and_more'),
        ('projects', '0004_projectrole_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectroleallocation',
            name='assigned_role',
        ),
        migrations.RemoveField(
            model_name='projectroleallocation',
            name='role',
        ),
        migrations.AddField(
            model_name='projectroleallocation',
            name='job_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_allocations', to='employees.jobtitle'),
        ),
    ]
