# Generated by Django 5.0.8 on 2026-07-19 18:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('projects', '0004_activityresource_hired_from_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityresource',
            name='company_tool_item',
        ),
        migrations.AddField(
            model_name='activityresource',
            name='inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventoryitem'),
        ),
        migrations.CreateModel(
            name='ProjectResourceAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resource_type', models.CharField(choices=[('company_tool', 'Company Tool'), ('money', 'Money')], max_length=20)),
                ('tool_name', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('allocated_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('money_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('money_purpose', models.CharField(blank=True, max_length=255)),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('allocated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_allocations', to='projects.project')),
            ],
            options={
                'verbose_name': 'Project Resource Allocation',
                'verbose_name_plural': 'Project Resource Allocations',
                'ordering': ['resource_type', 'tool_name'],
            },
        ),
        migrations.AddField(
            model_name='activityresource',
            name='project_allocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_draws', to='projects.projectresourceallocation'),
        ),
    ]
