# Generated by Django 6.0.7 on 2026-08-08 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_project_public_location'),
        ('quotations', '0010_quotation_director_approval_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='quotations.quotation'),
        ),
    ]
