# Generated by Django 6.0.7 on 2026-08-19 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_project_quotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Cover image for public portfolio', null=True, upload_to='project_covers/'),
        ),
        migrations.AddField(
            model_name='project',
            name='cover_image_url',
            field=models.URLField(blank=True, help_text='External URL for cover image as alternative'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Whether this project is published to the public website'),
        ),
        migrations.AddField(
            model_name='project',
            name='public_description',
            field=models.TextField(blank=True, help_text='Description shown on public website'),
        ),
    ]
