# Generated by Django 6.0.7 on 2026-08-19 06:01

import projects.models
import projects.models_extras
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_project_cover_image_project_cover_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityimage',
            name='image',
            field=models.ImageField(upload_to=projects.models_extras.activity_image_upload_to),
        ),
        migrations.AlterField(
            model_name='project',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Cover image for public portfolio', null=True, upload_to=projects.models.project_cover_upload_to),
        ),
    ]
