# Generated by Django 6.0.7 on 2026-08-19 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_alter_activityimage_image_alter_project_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='approach',
            field=models.TextField(blank=True, help_text='What SWS actually did - scope of work, phases, methods'),
        ),
        migrations.AddField(
            model_name='project',
            name='challenge',
            field=models.TextField(blank=True, help_text='The problem or situation that prompted the project'),
        ),
        migrations.AddField(
            model_name='project',
            name='result_coverage',
            field=models.CharField(blank=True, help_text='Coverage/scale (e.g., hectares, households served)', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='result_delivery_timing',
            field=models.CharField(blank=True, help_text='Delivery timing note (on schedule / duration)', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='result_infrastructure',
            field=models.CharField(blank=True, help_text='Infrastructure laid (pipeline length, etc.)', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='result_other',
            field=models.CharField(blank=True, help_text='Other project-specific measurable outcome', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='result_units_installed',
            field=models.CharField(blank=True, help_text='Units installed (pumps, boreholes, tanks, etc.)', max_length=255),
        ),
    ]
