# Generated by Django 6.0.7 on 2026-08-19 20:38

import projects.models_extras
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_project_approach_project_challenge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityimage',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='activityimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=projects.models_extras.activity_image_upload_to),
        ),
    ]
