# Generated by Django 6.0.7 on 2026-08-19 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_activityimage_image_url_alter_activityimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityimage',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.projectactivity'),
        ),
    ]
