# Generated by Django 6.0.7 on 2026-08-21 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_alter_activityimage_activity'),
        ('users', '0006_userprofile_account_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='approval_notes',
            field=models.TextField(blank=True, help_text='Notes about project approval'),
        ),
        migrations.AddField(
            model_name='project',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_projects', to='users.userprofile'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Pending Approval'), ('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], default='not_started', max_length=20),
        ),
    ]
