# Generated by Django 6.0.7 on 2026-09-03 07:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_project_approval_notes_project_approved_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFundTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expense_type', models.CharField(choices=[('TOOL_HIRE', 'Tool Hire'), ('TRANSPORT', 'Transport'), ('FUEL', 'Fuel'), ('ACCOMMODATION', 'Accommodation'), ('MATERIALS', 'Materials'), ('LABOUR', 'Labour'), ('EQUIPMENT', 'Equipment'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_date', models.DateField()),
                ('supplier_or_payee', models.CharField(blank=True, max_length=255)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('receipt_or_document', models.FileField(blank=True, null=True, upload_to='fund_receipts/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fund_transactions', to='projects.projectactivity')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_transactions', to='projects.project')),
                ('resource_allocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fund_transactions', to='projects.projectresourceallocation')),
                ('spent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fund_transactions_spent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project Fund Transaction',
                'verbose_name_plural': 'Project Fund Transactions',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
    ]
