# Generated by Django 6.0.7 on 2026-09-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_projectfundtransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecthistory',
            name='event_type',
            field=models.CharField(choices=[('created', 'Created'), ('team_changed', 'Team Changed'), ('milestone_updated', 'Milestone Updated'), ('status_changed', 'Status Changed'), ('cost_recorded', 'Cost Recorded'), ('document_added', 'Document Added'), ('completed', 'Completed'), ('resource_allocated', 'Resource Allocated'), ('resource_requested', 'Resource Requested'), ('resource_approved', 'Resource Approved'), ('resource_rejected', 'Resource Rejected'), ('resource_issued', 'Resource Issued'), ('resource_returned', 'Resource Returned'), ('resource_damaged', 'Resource Damaged'), ('resource_lost', 'Resource Lost'), ('fund_allocated', 'Fund Allocated'), ('fund_requested', 'Fund Requested'), ('fund_approved', 'Fund Approved'), ('fund_rejected', 'Fund Rejected'), ('fund_utilised', 'Fund Utilised'), ('project_extended', 'Project Extended')], max_length=30),
        ),
    ]
