# Generated by Django 6.0.7 on 2026-09-06 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_alter_projecthistory_event_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectroleallocation',
            name='is_team_lead',
        ),
        migrations.AddField(
            model_name='projectroleallocation',
            name='project_role',
            field=models.ForeignKey(blank=True, help_text='Project-specific role (e.g., Clerk of Works, Site Manager)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocations', to='projects.projectrole'),
        ),
    ]
