# Generated by Django 5.0.8 on 2026-07-16 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('assigned', 'Assigned'), ('not_active', 'Not Active')], default='active', max_length=20),
        ),
    ]
