# Generated by Django 5.0.8 on 2026-07-16 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_status'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeassignment',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_assignments', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='employeeassignment',
            name='project_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
