# Generated by Django 5.0.8 on 2026-07-16 20:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employeeassignment_project_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?[\\d\\s-]+$')])),
                ('address', models.TextField(blank=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=100)),
                ('emergency_phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^\\+?[\\d\\s-]+$')])),
                ('skills', models.TextField(blank=True, help_text='List of skills separated by commas')),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='UGX', max_length=3)),
                ('joining_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('assigned', 'Assigned'), ('not_active', 'Not Active')], default='active', max_length=20)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='employees/temporary/profiles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Temporary Employees',
                'ordering': ['employee_id'],
            },
        ),
        migrations.RemoveField(
            model_name='contract',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='employeehistory',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='employeedocument',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='employeeassignment',
            name='employee',
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(choices=[('permanent', 'Permanent'), ('fixed_term', 'Fixed Term'), ('probation', 'Probation')], max_length=20),
        ),
        migrations.AlterField(
            model_name='contract',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='employees/permanent/contracts/'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employmenttype',
            name='name',
            field=models.CharField(choices=[('permanent', 'Permanent'), ('temporary', 'Temporary')], max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='PermanentEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?[\\d\\s-]+$')])),
                ('address', models.TextField(blank=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=100)),
                ('emergency_phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^\\+?[\\d\\s-]+$')])),
                ('joining_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('not_active', 'Not Active')], default='active', max_length=20)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='employees/permanent/profiles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permanent_employees', to='employees.department')),
                ('job_title', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permanent_employees', to='employees.jobtitle')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='employees.permanentemployee')),
            ],
            options={
                'verbose_name_plural': 'Permanent Employees',
                'ordering': ['employee_id'],
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='permanent_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='employees.permanentemployee'),
        ),
        migrations.AddField(
            model_name='employeeassignment',
            name='permanent_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='employees.permanentemployee'),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='permanent_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='employees.permanentemployee'),
        ),
        migrations.AddField(
            model_name='employeehistory',
            name='permanent_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='employees.permanentemployee'),
        ),
        migrations.AddField(
            model_name='employeeassignment',
            name='temporary_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='employees.temporaryemployee'),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='temporary_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='employees.temporaryemployee'),
        ),
        migrations.AddField(
            model_name='employeehistory',
            name='temporary_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='employees.temporaryemployee'),
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
