# Generated by Django 5.0.8 on 2026-07-16 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_temporaryemployee_remove_contract_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permanentemployee',
            name='employee_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='temporaryemployee',
            name='employee_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
