# Generated by Django 5.0.8 on 2026-07-16 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_permanentemployee_employee_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='temporary_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='employees.temporaryemployee'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='employees/contracts/'),
        ),
    ]
