# Generated by Django 5.0.8 on 2026-07-19 11:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_contract_temporary_employee_alter_contract_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeassignment',
            name='permanent_employee',
        ),
        migrations.RemoveField(
            model_name='employeeassignment',
            name='project',
        ),
        migrations.RemoveField(
            model_name='employeeassignment',
            name='temporary_employee',
        ),
        migrations.RemoveField(
            model_name='permanentemployee',
            name='department',
        ),
        migrations.RemoveField(
            model_name='permanentemployee',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='permanentemployee',
            name='supervisor',
        ),
        migrations.RemoveField(
            model_name='employeehistory',
            name='permanent_employee',
        ),
        migrations.RemoveField(
            model_name='employeedocument',
            name='permanent_employee',
        ),
        migrations.RemoveField(
            model_name='employeedocument',
            name='temporary_employee',
        ),
        migrations.RemoveField(
            model_name='employeehistory',
            name='temporary_employee',
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name'], 'verbose_name_plural': 'Departments'},
        ),
        migrations.RemoveField(
            model_name='department',
            name='description',
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('technical', 'Technical Department'), ('casual', 'Casual Department'), ('management', 'Management')], max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?[\\d\\s-]+$')])),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('national_id', models.CharField(blank=True, max_length=30)),
                ('employee_type', models.CharField(choices=[('permanent', 'Permanent'), ('temporary', 'Temporary')], max_length=10)),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('wage_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('contract_start_date', models.DateField(blank=True, null=True)),
                ('contract_end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('not_active', 'Not active'), ('active_assigned', 'Active - assigned'), ('active_not_assigned', 'Active - not assigned')], default='not_active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.department')),
            ],
            options={
                'verbose_name_plural': 'Employees',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('doc_type', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='contracts/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_documents', to='employees.employee')),
            ],
            options={
                'verbose_name_plural': 'Contract Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='employeehistory',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='employees.employee'),
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
        migrations.DeleteModel(
            name='EmployeeAssignment',
        ),
        migrations.DeleteModel(
            name='PermanentEmployee',
        ),
        migrations.DeleteModel(
            name='TemporaryEmployee',
        ),
    ]
