# Generated by Django 5.0.8 on 2026-07-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_remove_employeeassignment_permanent_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('technical', 'Technical Department'), ('casual', 'Casual Department'), ('management', 'Management'), ('human_resource', 'Human Resource')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='employeehistory',
            name='action',
            field=models.CharField(choices=[('registered', 'Employee Registered'), ('contract_renewed', 'Contract Renewed'), ('position_changed', 'Position Changed'), ('department_changed', 'Department Changed'), ('status_changed', 'Status Changed'), ('salary_changed', 'Salary Changed'), ('assignment_added', 'Assignment Added'), ('assignment_ended', 'Assignment Ended'), ('document_uploaded', 'Document Uploaded'), ('field_updated', 'Field Updated'), ('other', 'Other')], max_length=30),
        ),
    ]
