# Generated by Django 6.0.7 on 2026-07-30 00:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_alter_department_name_alter_employeehistory_action'),
    ]

    operations = [
        # Alter department choices
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('technical', 'Technical'), ('administration', 'Administration'), ('human_resource', 'Human Resource')], max_length=30, unique=True),
        ),
        # Alter employee fields
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_type',
            field=models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time')], max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='full_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='employee',
            name='job_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.jobtitle'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('not_active', 'Not active'), ('active_assigned', 'Active - assigned'), ('active_not_assigned', 'Active - not assigned')], default='active_not_assigned', max_length=25),
        ),
        # Alter employment type choices
        migrations.AlterField(
            model_name='employmenttype',
            name='name',
            field=models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time')], max_length=20, unique=True),
        ),
        # Alter employee document model
        migrations.AlterUniqueTogether(
            name='employeedocument',
            unique_together={('employee', 'document_type')},
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='document_type',
            field=models.CharField(choices=[('identity', 'Identity Document'), ('contact', 'Contact'), ('cv', 'Experience / CV'), ('reference', 'Reference')], max_length=20),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='file',
            field=models.FileField(upload_to='employee_docs/'),
        ),
        migrations.RemoveField(
            model_name='employeedocument',
            name='description',
        ),
        migrations.RemoveField(
            model_name='employeedocument',
            name='title',
        ),
    ]
