# Generated by Django 6.0.7 on 2026-07-30 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_employment_management_updates'),
    ]

    operations = [
        # Add missing department column only (job_title already exists)
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.department'),
        ),
    ]
