# Generated by Django 6.0.7 on 2026-07-30 00:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_fix_employee_foreign_keys'),
    ]

    operations = [
        # Add only management_category (other fields already exist)
        migrations.AddField(
            model_name='employee',
            name='management_category',
            field=models.CharField(blank=True, choices=[('management', 'Management (Administrative)'), ('technical', 'Technical / Field')], max_length=20, null=True),
        ),
    ]
