# Generated by Django 6.0.7 on 2026-07-30 04:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_add_missing_employee_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='wage_rate',
            new_name='daily_rate',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='salary',
            new_name='gross_monthly_salary',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='national_id',
        ),
        migrations.AddField(
            model_name='employee',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='id_document',
            field=models.FileField(blank=True, null=True, upload_to='employee_docs/identity/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AddField(
            model_name='employee',
            name='id_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='id_type',
            field=models.CharField(blank=True, choices=[('national_id', 'National ID'), ('driving_permit', 'Driving Permit'), ('passport', 'Passport'), ('refugee_card', 'Refugee Card')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='pay_basis',
            field=models.CharField(blank=True, choices=[('daily_fixed', 'Fixed rate per day worked'), ('hourly_daily', 'Hourly rate, calculated daily'), ('hourly_monthly', 'Hourly rate, totaled monthly')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('technical', 'Technical'), ('management', 'Management'), ('project_management', 'Project Management'), ('human_resource', 'Human Resource')], max_length=30, unique=True),
        ),
    ]
