# Generated by Django 6.0.7 on 2026-07-30 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0014_department_description_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('assigned', 'Assigned'), ('suspended', 'Suspended'), ('on_leave', 'On Leave'), ('contract_expired', 'Contract Expired')], default='available', max_length=25),
        ),
    ]
