# Generated by Django 6.0.7 on 2026-07-30 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0016_department_department_head_department_description_and_more'),
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='default_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='roles.role'),
        ),
    ]
