# Generated by Django 6.0.7 on 2026-08-04 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0019_department_description_alter_employee_job_title'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE employees_employee ALTER COLUMN job_title_id DROP NOT NULL;",
            reverse_sql="ALTER TABLE employees_employee ALTER COLUMN job_title_id SET NOT NULL;"
        ),
    ]
