# Generated by Django 6.0.7 on 2026-08-04 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0020_auto_20260804_0721'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE employees_employee DROP COLUMN IF EXISTS status_extended;",
            reverse_sql="-- No reverse SQL needed"
        ),
    ]
