# Generated by Django 6.0.7 on 2026-08-08 05:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0024_employee_deceased_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='available_from',
            field=models.DateField(blank=True, help_text='Date when employee becomes available', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='available_until',
            field=models.DateField(blank=True, help_text='Date until employee remains available', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='current_workload_percentage',
            field=models.PositiveIntegerField(default=0, help_text='Current workload percentage (0-100)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='max_workload_percentage',
            field=models.PositiveIntegerField(default=100, help_text='Maximum workload percentage allowed'),
        ),
        migrations.AddField(
            model_name='employee',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional availability notes'),
        ),
        migrations.AddField(
            model_name='employee',
            name='preferred_hours_end',
            field=models.TimeField(blank=True, help_text='Preferred end time', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='preferred_hours_start',
            field=models.TimeField(blank=True, help_text='Preferred start time', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='preferred_work_days',
            field=models.CharField(blank=True, help_text='Preferred work days (e.g., Mon-Fri)', max_length=50),
        ),
        migrations.CreateModel(
            name='EmployeeSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proficiency', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='intermediate', max_length=20)),
                ('years_experience', models.PositiveIntegerField(default=0)),
                ('certified', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='employees.employee')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='employees.skill')),
            ],
            options={
                'ordering': ['skill__name'],
                'unique_together': {('employee', 'skill')},
            },
        ),
    ]
