# Generated by Django 6.0.7 on 2026-08-08 05:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0025_skill_department_description_employee_available_from_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_reference', models.CharField(help_text='Reference to the project (e.g., PRJ-2026-000001)', max_length=150)),
                ('role', models.CharField(choices=[('project_manager', 'Project Manager'), ('site_supervisor', 'Site Supervisor'), ('engineer', 'Engineer'), ('technician', 'Technician'), ('laborer', 'Laborer'), ('driver', 'Driver'), ('other', 'Other')], max_length=20)),
                ('workload_percentage', models.PositiveIntegerField(default=0, help_text='Workload percentage for this assignment (0-100)')),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('active', 'Active'), ('completed', 'Completed'), ('withdrawn', 'Withdrawn')], default='assigned', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_assignments', to='employees.employee')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['employee'], name='employees_p_employ_8f5c8b_idx'), models.Index(fields=['project_reference'], name='employees_p_projec_8c2c6d_idx'), models.Index(fields=['status'], name='employees_p_status_5e5f5a_idx'), models.Index(fields=['assigned_at'], name='employees_p_assign_3b2c2a_idx')],
            },
        ),
    ]
