# Generated by Django 6.0.7 on 2026-08-16 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0026_project_assignment'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='projectassignment',
            new_name='employees_p_employe_15bd24_idx',
            old_name='employees_p_employ_8f5c8b_idx',
        ),
        migrations.RenameIndex(
            model_name='projectassignment',
            new_name='employees_p_project_8e6259_idx',
            old_name='employees_p_projec_8c2c6d_idx',
        ),
        migrations.RenameIndex(
            model_name='projectassignment',
            new_name='employees_p_status_fdd41e_idx',
            old_name='employees_p_status_5e5f5a_idx',
        ),
        migrations.RenameIndex(
            model_name='projectassignment',
            new_name='employees_p_assigne_c2063a_idx',
            old_name='employees_p_assign_3b2c2a_idx',
        ),
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
