# Generated by Django 5.0.8 on 2026-07-20 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('HR', 'Human Resources'), ('INVENTORY', 'Inventory'), ('PROJECTS', 'Projects'), ('TENDERS', 'Tenders'), ('CRM', 'Customer Relationship Management'), ('FINANCIAL', 'Financial'), ('SUPPLIERS', 'Suppliers')], max_length=20)),
                ('record_id', models.IntegerField()),
                ('record_name', models.CharField(max_length=255)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('status_changed', 'Status Changed'), ('assigned', 'Assigned'), ('unassigned', 'Unassigned'), ('uploaded', 'Uploaded'), ('downloaded', 'Downloaded'), ('exported', 'Exported'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('previous_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['module', '-timestamp'], name='core_auditl_module_8dce1c_idx'), models.Index(fields=['record_id'], name='core_auditl_record__5018f5_idx'), models.Index(fields=['performed_by'], name='core_auditl_perform_508dbf_idx')],
            },
        ),
    ]
