# Generated by Django 6.0.7 on 2026-08-08 05:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_type', models.CharField(choices=[('funnel', 'Sales Funnel'), ('pipeline', 'Sales Pipeline'), ('revenue', 'Revenue'), ('projects', 'Projects'), ('employees', 'Employees'), ('inventory', 'Inventory')], max_length=20)),
                ('metric_name', models.CharField(max_length=100)),
                ('metric_value', models.JSONField(default=dict)),
                ('period', models.CharField(default='daily', max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-period_end', 'metric_type'],
                'indexes': [models.Index(fields=['metric_type'], name='analytics_d_metric__a4e62a_idx'), models.Index(fields=['period'], name='analytics_d_period_d27e50_idx'), models.Index(fields=['period_end'], name='analytics_d_period__528d7a_idx')],
                'unique_together': {('metric_type', 'metric_name', 'period', 'period_start', 'period_end')},
            },
        ),
        migrations.CreateModel(
            name='InventoryMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_items', models.PositiveIntegerField(default=0)),
                ('low_stock_items', models.PositiveIntegerField(default=0)),
                ('out_of_stock_items', models.PositiveIntegerField(default=0)),
                ('total_inventory_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_procurement_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('average_stock_turnover_days', models.PositiveIntegerField(default=0)),
                ('stockout_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('period', models.CharField(default='monthly', max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-period_end'],
                'indexes': [models.Index(fields=['period'], name='analytics_i_period_fe0c00_idx'), models.Index(fields=['period_end'], name='analytics_i_period__c842b9_idx')],
                'unique_together': {('period', 'period_start', 'period_end')},
            },
        ),
        migrations.CreateModel(
            name='ProjectMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_projects', models.PositiveIntegerField(default=0)),
                ('active_projects', models.PositiveIntegerField(default=0)),
                ('completed_projects', models.PositiveIntegerField(default=0)),
                ('on_hold_projects', models.PositiveIntegerField(default=0)),
                ('total_project_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('average_project_duration_days', models.PositiveIntegerField(default=0)),
                ('on_time_completion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_employees', models.PositiveIntegerField(default=0)),
                ('active_employees', models.PositiveIntegerField(default=0)),
                ('average_workload_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('period', models.CharField(default='monthly', max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-period_end'],
                'indexes': [models.Index(fields=['period'], name='analytics_p_period_e7789d_idx'), models.Index(fields=['period_end'], name='analytics_p_period__6ba387_idx')],
                'unique_together': {('period', 'period_start', 'period_end')},
            },
        ),
        migrations.CreateModel(
            name='RevenueMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revenue_type', models.CharField(choices=[('total', 'Total Revenue'), ('project', 'Project Revenue'), ('service', 'Service Revenue'), ('product', 'Product Revenue')], max_length=20)),
                ('gross_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('net_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cost_of_goods_sold', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('gross_profit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('gross_margin', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('operating_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('operating_profit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('operating_margin', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('growth_rate', models.DecimalField(decimal_places=2, default=0, help_text='Growth rate compared to previous period', max_digits=5)),
                ('period', models.CharField(default='monthly', max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-period_end'],
                'indexes': [models.Index(fields=['revenue_type'], name='analytics_r_revenue_a56575_idx'), models.Index(fields=['period'], name='analytics_r_period_73158a_idx'), models.Index(fields=['period_end'], name='analytics_r_period__052c51_idx')],
                'unique_together': {('revenue_type', 'period', 'period_start', 'period_end')},
            },
        ),
        migrations.CreateModel(
            name='SalesFunnelMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', models.CharField(choices=[('lead', 'Lead'), ('qualified', 'Qualified'), ('quotation_sent', 'Quotation Sent'), ('quotation_review', 'Quotation Review'), ('quotation_approved', 'Quotation Approved'), ('accepted', 'Accepted'), ('project_created', 'Project Created'), ('completed', 'Completed')], max_length=30)),
                ('count', models.PositiveIntegerField(default=0)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=0, help_text='Conversion rate from previous stage', max_digits=5)),
                ('period', models.CharField(default='monthly', max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-period_end', 'stage'],
                'indexes': [models.Index(fields=['stage'], name='analytics_s_stage_6b462b_idx'), models.Index(fields=['period'], name='analytics_s_period_b13e6e_idx'), models.Index(fields=['period_end'], name='analytics_s_period__5ba0b7_idx')],
                'unique_together': {('stage', 'period', 'period_start', 'period_end')},
            },
        ),
        migrations.CreateModel(
            name='SalesPipelineMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_leads', models.PositiveIntegerField(default=0)),
                ('qualified_leads', models.PositiveIntegerField(default=0)),
                ('quotations_sent', models.PositiveIntegerField(default=0)),
                ('quotations_accepted', models.PositiveIntegerField(default=0)),
                ('quotations_rejected', models.PositiveIntegerField(default=0)),
                ('total_quotation_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('won_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('lost_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('win_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('average_deal_size', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('average_sales_cycle_days', models.PositiveIntegerField(default=0)),
                ('period', models.CharField(default='monthly', max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-period_end'],
                'indexes': [models.Index(fields=['period'], name='analytics_s_period_672624_idx'), models.Index(fields=['period_end'], name='analytics_s_period__fe4126_idx')],
                'unique_together': {('period', 'period_start', 'period_end')},
            },
        ),
    ]
