# Generated by Django 6.0.7 on 2026-08-29 10:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('site_visit', 'Site Visit'), ('follow_up', 'Follow Up'), ('meeting', 'Meeting'), ('task', 'Task'), ('quotation_expiry', 'Quotation Expiry')], max_length=20)),
                ('total_events', models.PositiveIntegerField(default=0)),
                ('completed_events', models.PositiveIntegerField(default=0)),
                ('pending_events', models.PositiveIntegerField(default=0)),
                ('cancelled_events', models.PositiveIntegerField(default=0)),
                ('completion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('period', models.CharField(default='monthly', max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-period_end', 'event_type'],
                'indexes': [models.Index(fields=['event_type'], name='analytics_c_event_t_e32305_idx'), models.Index(fields=['period'], name='analytics_c_period_8e014d_idx'), models.Index(fields=['period_end'], name='analytics_c_period__88e1a5_idx')],
                'unique_together': {('event_type', 'period', 'period_start', 'period_end')},
            },
        ),
    ]
