# Generated by Django 6.0.7 on 2026-08-16 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_servicefaq'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesection',
            name='alt_text_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='servicesection',
            name='alt_text_3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='servicesection',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='service_images/sections/'),
        ),
        migrations.AddField(
            model_name='servicesection',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='service_images/sections/'),
        ),
        migrations.AddField(
            model_name='servicesection',
            name='image_url_2',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='servicesection',
            name='image_url_3',
            field=models.URLField(blank=True),
        ),
    ]
