# Generated by Django 6.0.7 on 2026-08-16 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_servicesection_alt_text_2_servicesection_alt_text_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='hero_alt_text_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='service',
            name='hero_alt_text_3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='service',
            name='hero_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='service_images/heroes/'),
        ),
        migrations.AddField(
            model_name='service',
            name='hero_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='service_images/heroes/'),
        ),
        migrations.AddField(
            model_name='service',
            name='hero_image_url_2',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='hero_image_url_3',
            field=models.URLField(blank=True),
        ),
    ]
