# Generated by Django 6.0.7 on 2026-08-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_mediafolder'),
        ('services', '0008_service_hero_alt_text_2_service_hero_alt_text_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='gallery_images',
            field=models.ManyToManyField(blank=True, help_text='Images to display in the service gallery', related_name='services', to='content.mediaasset'),
        ),
    ]
