# Generated by Django 5.0.8 on 2026-08-11 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_requests_issued', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='request_number',
            field=models.CharField(blank=True, editable=False, max_length=32, unique=True),
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='review_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_requests_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='materialrequestitem',
            name='quantity_issued',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='product',
            name='warehouse',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='materialrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('INVALID', 'Invalid')], default='PENDING', max_length=16),
        ),
    ]
