# Generated by Django 6.0.7 on 2026-07-20 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_materialrequest_rejected_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='item_code',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
