# Generated by Django 6.0.7 on 2026-08-31 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_create_missing_tables'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialrequest',
            name='project',
        ),
        migrations.RemoveField(
            model_name='materialrequestitem',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='supplierquotation',
            name='material_request',
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='department',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_requests_issued', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='project_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='project_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='review_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_requests_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='materialrequestitem',
            name='quantity_approved',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='materialrequestitem',
            name='quantity_issued',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='materialrequestitem',
            name='quantity_requested',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='materialrequest',
            name='request_number',
            field=models.CharField(blank=True, editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='materialrequest',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='materialrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('INVALID', 'Invalid')], default='PENDING', max_length=16),
        ),
        migrations.AlterField(
            model_name='materialrequestitem',
            name='inventory_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.inventoryitem'),
        ),
        migrations.AlterField(
            model_name='supplierquotation',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('RECEIVED', 'Received'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=16),
        ),
        migrations.AlterField(
            model_name='supplierquotation',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_quotations', to='inventory.supplier'),
        ),
        migrations.AlterField(
            model_name='supplierquotationitem',
            name='inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.inventoryitem'),
        ),
        migrations.AlterField(
            model_name='supplierquotationitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='supplierquotationitem',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
