# Generated by Django 6.0.7 on 2026-09-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_purchase_number_sequence'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE inventory_supplier ALTER COLUMN supplier_code DROP NOT NULL;",
            reverse_sql="ALTER TABLE inventory_supplier ALTER COLUMN supplier_code SET NOT NULL;"
        ),
    ]
