# Generated by Django 6.0.7 on 2026-09-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_category_is_archived_supplier_supplier_code'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE inventory_supplier ALTER COLUMN notes DROP NOT NULL;",
            reverse_sql="ALTER TABLE inventory_supplier ALTER COLUMN notes SET NOT NULL;"
        ),
    ]
