# Generated by Django 6.0.7 on 2026-09-03 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_category_is_archived_supplier_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='initial_stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
