# Generated by Django 6.0.7 on 2026-09-03 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_category_is_archived_inventoryitem_initial_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='material_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='inventory.materialrequest'),
        ),
    ]
