# Generated by Django 6.0.7 on 2026-09-03 07:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_category_is_archived_stockmovement_material_request_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='inventory_type',
            field=models.CharField(choices=[('MATERIAL', 'Material'), ('COMPANY_TOOL', 'Company Tool')], default='MATERIAL', help_text='Distinguish between consumable materials and reusable company tools', max_length=20),
        ),
        migrations.AddField(
            model_name='materialrequestitem',
            name='actual_return_date',
            field=models.DateField(blank=True, help_text='Actual return date', null=True),
        ),
        migrations.AddField(
            model_name='materialrequestitem',
            name='condition_at_issue',
            field=models.CharField(blank=True, help_text='Condition when issued', max_length=20),
        ),
        migrations.AddField(
            model_name='materialrequestitem',
            name='condition_at_return',
            field=models.CharField(blank=True, help_text='Condition when returned', max_length=20),
        ),
        migrations.AddField(
            model_name='materialrequestitem',
            name='expected_return_date',
            field=models.DateField(blank=True, help_text='Expected return date for company tools', null=True),
        ),
        migrations.AddField(
            model_name='materialrequestitem',
            name='responsible_person',
            field=models.ForeignKey(blank=True, help_text='Person responsible for the issued tool', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tool_issuances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='materialrequestitem',
            name='return_notes',
            field=models.TextField(blank=True, help_text='Notes about tool return'),
        ),
        migrations.CreateModel(
            name='ToolAccountability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_id', models.UUIDField(blank=True, help_text='Soft reference to project', null=True)),
                ('project_name', models.CharField(blank=True, max_length=255)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('expected_return_date', models.DateField(blank=True, null=True)),
                ('actual_return_date', models.DateField(blank=True, null=True)),
                ('condition_at_issue', models.CharField(blank=True, max_length=20)),
                ('condition_at_return', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('PENDING_RETURN', 'Pending Return'), ('RETURNED_GOOD', 'Returned Good'), ('RETURNED_DAMAGED', 'Returned Damaged'), ('NOT_RETURNED', 'Not Returned'), ('LOST', 'Lost'), ('UNDER_REVIEW', 'Under Review'), ('ACCOUNTABILITY_RESOLVED', 'Accountability Resolved')], default='PENDING_RETURN', max_length=30)),
                ('damage_description', models.TextField(blank=True)),
                ('loss_description', models.TextField(blank=True)),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('resolution', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('accountable_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accountability_as_responsible', to=settings.AUTH_USER_MODEL)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_accountability', to=settings.AUTH_USER_MODEL)),
                ('material_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accountability_records', to='inventory.materialrequest')),
                ('material_request_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accountability_records', to='inventory.materialrequestitem')),
                ('responsible_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accountability_records', to=settings.AUTH_USER_MODEL)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accountability_records', to='inventory.inventoryitem')),
            ],
            options={
                'verbose_name': 'Tool Accountability',
                'verbose_name_plural': 'Tool Accountability Records',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
