# Generated by Django 5.0.8 on 2026-07-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CorePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(choices=[('HOME', 'Home'), ('ABOUT_US', 'About Us')], max_length=20)),
                ('section_name', models.CharField(max_length=100)),
                ('section_order', models.IntegerField(default=0)),
                ('content', models.TextField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Core Page',
                'verbose_name_plural': 'Core Pages',
                'ordering': ['page_type', 'section_order'],
                'unique_together': {('page_type', 'section_name')},
            },
        ),
    ]
