# Generated by Django 5.0.8 on 2026-07-15 08:50

import core_pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='corepage',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Alt text for accessibility', max_length=200),
        ),
        migrations.AddField(
            model_name='corepage',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload image for this section', null=True, upload_to=core_pages.models.upload_to),
        ),
        migrations.AddField(
            model_name='corepage',
            name='section_type',
            field=models.CharField(choices=[('HERO', 'Hero Section'), ('FEATURE', 'Feature Section'), ('BACKGROUND', 'Background'), ('GALLERY', 'Gallery'), ('BANNER', 'Banner'), ('THUMBNAIL', 'Thumbnail')], default='BACKGROUND', max_length=20),
        ),
        migrations.AlterField(
            model_name='corepage',
            name='content',
            field=models.TextField(blank=True, help_text='Optional text content for this section'),
        ),
        migrations.AlterField(
            model_name='corepage',
            name='image_url',
            field=models.URLField(blank=True, help_text='Alternative: use external image URL', null=True),
        ),
        migrations.AlterField(
            model_name='corepage',
            name='page_type',
            field=models.CharField(choices=[('HOME', 'Home'), ('ABOUT_US', 'About Us'), ('SERVICES', 'Services'), ('CONTACT', 'Contact'), ('PROJECTS', 'Projects'), ('BLOG', 'Blog')], max_length=20),
        ),
    ]
