# Generated by Django 5.0.8 on 2026-07-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_pages', '0002_corepage_alt_text_corepage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corepage',
            name='page_type',
            field=models.CharField(choices=[('HOME', 'Home'), ('ABOUT_US', 'About Us'), ('SERVICES', 'Services'), ('CONTACT', 'Contact'), ('PROJECTS', 'Projects'), ('BLOG', 'Blog'), ('QUOTATIONS', 'Quotations')], max_length=20),
        ),
        migrations.AlterField(
            model_name='corepage',
            name='section_type',
            field=models.CharField(choices=[('HERO', 'Hero Section'), ('FEATURE', 'Feature Section'), ('BACKGROUND', 'Background'), ('GALLERY', 'Gallery'), ('BANNER', 'Banner'), ('THUMBNAIL', 'Thumbnail'), ('TEAM', 'Team Section'), ('VALUES', 'Values Section'), ('SERVICE_ICON', 'Service Icon'), ('MAP', 'Map Section'), ('CONTACT_INFO', 'Contact Info')], default='BACKGROUND', max_length=20),
        ),
    ]
