# Generated by Django 6.0.7 on 2026-07-29 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_pages', '0003_alter_corepage_page_type_alter_corepage_section_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, help_text='Emoji or icon identifier', max_length=10)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Core Value',
                'verbose_name_plural': 'Core Values',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('role_title', models.CharField(max_length=150)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team_photos/')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='PageField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Home'), ('about', 'About Us'), ('blog', 'Blog'), ('contact', 'Contact'), ('projects', 'Projects'), ('quotation', 'Request Quotation'), ('services', 'Services Overview')], max_length=30)),
                ('key', models.CharField(help_text='e.g. hero_headline, phone, business_hours', max_length=100)),
                ('label', models.CharField(help_text='Human-readable label shown to admin', max_length=150)),
                ('field_type', models.CharField(choices=[('text', 'Short Text'), ('richtext', 'Paragraph')], default='text', max_length=20)),
                ('value', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Page Field',
                'verbose_name_plural': 'Page Fields',
                'ordering': ['page', 'display_order'],
                'unique_together': {('page', 'key')},
            },
        ),
        migrations.CreateModel(
            name='PageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Home'), ('about', 'About Us'), ('blog', 'Blog'), ('contact', 'Contact'), ('projects', 'Projects'), ('quotation', 'Request Quotation'), ('services', 'Services Overview')], max_length=30)),
                ('key', models.CharField(help_text='e.g. hero_background, company_image', max_length=100)),
                ('label', models.CharField(help_text='Human-readable label shown to admin', max_length=150)),
                ('image', models.ImageField(upload_to='website_images/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Page Image',
                'verbose_name_plural': 'Page Images',
                'unique_together': {('page', 'key')},
            },
        ),
    ]
