# Generated by Django 6.0.7 on 2026-08-06 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_pages', '0005_pageimage_optional_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageimage',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL as alternative to upload', null=True),
        ),
    ]
