# Generated by Django 6.0.7 on 2026-08-06 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_pages', '0009_add_contact_hero_image_slots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagefield',
            name='page',
            field=models.CharField(help_text='Page identifier (e.g., home, about, service-water-treatment)', max_length=100),
        ),
        migrations.AlterField(
            model_name='pageimage',
            name='page',
            field=models.CharField(help_text='Page identifier (e.g., home, about, service-water-treatment)', max_length=100),
        ),
    ]
