# Generated by Django 6.0.7 on 2026-08-19 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_pages', '0010_alter_pagefield_page_alter_pageimage_page'),
        ('employees', '0027_rename_employees_p_employ_8f5c8b_idx_employees_p_employe_15bd24_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='employee',
            field=models.ForeignKey(blank=True, help_text="Link to existing employee (optional). If set, will use employee's photo and basic info.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_member_profile', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='bio',
            field=models.TextField(blank=True, help_text='Professional bio for website'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='name',
            field=models.CharField(help_text='Override employee name if needed', max_length=150),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(blank=True, help_text='Override employee photo if needed', null=True, upload_to='team_photos/'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role_title',
            field=models.CharField(help_text='Override employee role for website display', max_length=150),
        ),
    ]
