# Generated by Django 5.0.8 on 2026-07-14 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('EXECUTIVE', 'Executive'), ('PROJECT', 'Project'), ('FINANCIAL', 'Financial'), ('TENDER', 'Tender'), ('INVENTORY', 'Inventory'), ('CRM', 'CRM')], max_length=30)),
                ('report_type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('READY', 'Ready'), ('FAILED', 'Failed')], default='QUEUED', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('file_format', models.CharField(choices=[('PDF', 'PDF'), ('XLSX', 'Excel')], default='PDF', max_length=10)),
                ('date_range_start', models.DateField(blank=True, null=True)),
                ('date_range_end', models.DateField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ['-requested_at'],
            },
        ),
    ]
