# Generated by Django 6.0.7 on 2026-08-06 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('projects', '0015_project_public_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_assets', to='projects.project'),
        ),
    ]
