# Generated by Django 6.0.7 on 2026-08-02 09:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lead_number', models.CharField(max_length=50, unique=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('preferred_contact', models.CharField(blank=True, max_length=50, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('subcounty', models.CharField(blank=True, max_length=100, null=True)),
                ('village', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('gps', models.CharField(blank=True, max_length=100, null=True)),
                ('service', models.CharField(choices=[('borehole_drilling', 'Borehole Drilling'), ('solar_pump_installation', 'Solar Pump Installation'), ('water_treatment', 'Water Treatment'), ('pipeline_extension', 'Pipeline Extension'), ('plumbing', 'Plumbing'), ('water_storage', 'Water Storage'), ('maintenance', 'Maintenance'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('budget_range', models.CharField(blank=True, choices=[('under_10m', 'Under 10M'), ('10_50m', '10–50M'), ('50_100m', '50–100M'), ('100m_plus', '100M+'), ('not_sure', 'Not Sure')], max_length=50, null=True)),
                ('timeline', models.CharField(blank=True, choices=[('urgent', 'Urgent'), ('1_month', '1 Month'), ('3_months', '3 Months'), ('flexible', 'Flexible')], max_length=50, null=True)),
                ('source', models.CharField(choices=[('website', 'Website'), ('referral', 'Referral'), ('social_media', 'Social Media'), ('advertisement', 'Advertisement'), ('other', 'Other')], default='website', max_length=50)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('site_visit', 'Site Visit'), ('estimating', 'Estimating'), ('quotation', 'Quotation'), ('negotiation', 'Negotiation'), ('won', 'Won'), ('lost', 'Lost')], default='new', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(choices=[('note', 'Note'), ('call', 'Call'), ('email', 'Email'), ('site_visit', 'Site Visit'), ('status_change', 'Status Change'), ('assignment', 'Assignment'), ('quotation_sent', 'Quotation Sent'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='quotations.lead')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='LeadAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='lead_attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='quotations.lead')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('ground_conditions', models.TextField(blank=True, null=True)),
                ('water_source', models.TextField(blank=True, null=True)),
                ('depth_estimate', models.CharField(blank=True, max_length=100, null=True)),
                ('recommendations', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engineer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_visits', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_visits', to='quotations.lead')),
            ],
            options={
                'ordering': ['-scheduled_date'],
            },
        ),
    ]
