# Generated by Django 6.0.7 on 2026-08-02 09:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('service', models.CharField(choices=[('borehole_drilling', 'Borehole Drilling'), ('solar_pump_installation', 'Solar Pump Installation'), ('water_treatment', 'Water Treatment'), ('pipeline_extension', 'Pipeline Extension'), ('plumbing', 'Plumbing'), ('water_storage', 'Water Storage'), ('maintenance', 'Maintenance'), ('tank_installation', 'Tank Installation'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('header', models.TextField(blank=True, null=True)),
                ('terms', models.TextField(blank=True, null=True)),
                ('footer', models.TextField(blank=True, null=True)),
                ('validity_days', models.IntegerField(default=30)),
                ('payment_terms', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuotationTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('unit', models.CharField(choices=[('each', 'Each'), ('meter', 'Meter'), ('square_meter', 'Square Meter'), ('cubic_meter', 'Cubic Meter'), ('hour', 'Hour'), ('day', 'Day'), ('kg', 'Kilogram'), ('ton', 'Ton'), ('liter', 'Liter'), ('set', 'Set')], max_length=50)),
                ('default_quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('default_rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vat_percentage', models.DecimalField(decimal_places=2, default=18, max_digits=5)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_optional', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotations.quotationtemplate')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
