# Generated by Django 6.0.7 on 2026-08-07 19:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_project_public_location'),
        ('quotations', '0006_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('new_lead', 'New Lead'), ('lead_assigned', 'Lead Assigned'), ('quotation_submitted', 'Quotation Submitted'), ('quotation_approved', 'Quotation Approved'), ('quotation_sent', 'Quotation Sent'), ('quotation_accepted', 'Quotation Accepted'), ('quotation_rejected', 'Quotation Rejected'), ('task_assigned', 'Task Assigned'), ('task_due', 'Task Due'), ('site_visit_scheduled', 'Site Visit Scheduled'), ('site_visit_completed', 'Site Visit Completed'), ('project_created', 'Project Created'), ('project_updated', 'Project Updated')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead_notifications', to='quotations.lead')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_notifications', to='projects.project')),
                ('quotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotation_notifications', to='quotations.quotation')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_notifications', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_notifications', to='quotations.task')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
