# Generated by Django 6.0.7 on 2026-08-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0007_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitevisit',
            name='accessibility_notes',
            field=models.TextField(blank=True, help_text='Notes about site accessibility for equipment', null=True),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='distance_to_road',
            field=models.CharField(blank=True, help_text='Distance from main road', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='elevation',
            field=models.CharField(blank=True, help_text='Elevation above sea level', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='gps_accuracy',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='nearby_structures',
            field=models.TextField(blank=True, help_text='Nearby buildings, fences, etc.', null=True),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='photo_1',
            field=models.ImageField(blank=True, null=True, upload_to='site_visit_photos/'),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='photo_2',
            field=models.ImageField(blank=True, null=True, upload_to='site_visit_photos/'),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='photo_3',
            field=models.ImageField(blank=True, null=True, upload_to='site_visit_photos/'),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='photo_4',
            field=models.ImageField(blank=True, null=True, upload_to='site_visit_photos/'),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='photo_5',
            field=models.ImageField(blank=True, null=True, upload_to='site_visit_photos/'),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='site_area_size',
            field=models.CharField(blank=True, help_text='Size of the site area (e.g., 50x30 meters)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='soil_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='utilities_present',
            field=models.TextField(blank=True, help_text='Water, electricity, sewer lines nearby', null=True),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='vegetation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='weather_conditions',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
