# Generated by Django 6.0.7 on 2026-08-07 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0008_sitevisit_accessibility_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationtemplateitem',
            name='category',
            field=models.CharField(choices=[('material', 'Material'), ('labor', 'Labor'), ('equipment', 'Equipment'), ('transport', 'Transport'), ('overhead', 'Overhead'), ('other', 'Other')], default='material', max_length=50),
        ),
        migrations.AddField(
            model_name='quotationtemplateitem',
            name='is_required',
            field=models.BooleanField(default=True, help_text='Whether this item is required for the service'),
        ),
        migrations.AddField(
            model_name='quotationtemplateitem',
            name='item_code',
            field=models.CharField(blank=True, help_text='Item code for inventory reference', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quotationtemplateitem',
            name='max_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum quantity allowed', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='quotationtemplateitem',
            name='min_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum quantity allowed', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='quotationtemplateitem',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes for this item', null=True),
        ),
    ]
