# Generated by Django 6.0.7 on 2026-08-08 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0010_quotation_director_approval_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationitem',
            name='inventory_item',
            field=models.ForeignKey(blank=True, help_text='Link to inventory item for stock checking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_items', to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='item_code',
            field=models.CharField(blank=True, help_text='Item code for inventory reference', max_length=50, null=True),
        ),
    ]
