# Generated by Django 6.0.7 on 2026-08-21 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0011_quotationitem_inventory_item_quotationitem_item_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='hero_alt_text_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='hero_alt_text_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='hero_alt_text_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='hero_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='quotation_hero/'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='hero_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='quotation_hero/'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='hero_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='quotation_hero/'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='hero_image_url_1',
            field=models.URLField(blank=True, help_text='External URL for hero image 1'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='hero_image_url_2',
            field=models.URLField(blank=True, help_text='External URL for hero image 2'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='hero_image_url_3',
            field=models.URLField(blank=True, help_text='External URL for hero image 3'),
        ),
    ]
