# Generated by Django 6.0.7 on 2026-08-21 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0012_quotation_hero_alt_text_1_quotation_hero_alt_text_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_key', models.CharField(help_text='Key identifying the question', max_length=100)),
                ('question_text', models.CharField(help_text='The actual question asked', max_length=255)),
                ('answer', models.TextField(help_text="Customer's answer")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='quotations.lead')),
            ],
            options={
                'ordering': ['question_key'],
            },
        ),
    ]
