# Generated by Django 6.0.7 on 2026-08-22 06:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0013_leaddetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='customer_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('commercial', 'Commercial'), ('government', 'Government'), ('ngo', 'NGO'), ('institution', 'Institution')], default='individual', max_length=50),
        ),
        migrations.AddField(
            model_name='lead',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=50),
        ),
        migrations.AddField(
            model_name='lead',
            name='qualification_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='requirement_status',
            field=models.CharField(choices=[('information_incomplete', 'Information Incomplete'), ('requirements_confirmed', 'Requirements Confirmed')], default='information_incomplete', max_length=50),
        ),
        migrations.AlterField(
            model_name='lead',
            name='service',
            field=models.CharField(blank=True, choices=[('borehole_drilling', 'Borehole Drilling'), ('solar_pump_installation', 'Solar Pump Installation'), ('water_treatment', 'Water Treatment'), ('pipeline_extension', 'Pipeline Extension'), ('plumbing', 'Plumbing'), ('water_storage', 'Water Storage'), ('maintenance', 'Maintenance'), ('other', 'Other')], help_text='Legacy field - use LeadService for multi-service support', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualification', 'Qualification'), ('site_visit', 'Site Visit'), ('requirements_confirmed', 'Requirements Confirmed'), ('ready_for_quotation', 'Ready for Quotation'), ('quotation_draft', 'Quotation Draft'), ('internal_review', 'Internal Review'), ('quotation_sent', 'Quotation Sent'), ('negotiation', 'Negotiation'), ('won', 'Won'), ('lost', 'Lost')], default='new', max_length=50),
        ),
        migrations.CreateModel(
            name='LeadService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service', models.CharField(choices=[('borehole_drilling', 'Borehole Drilling'), ('solar_pump_installation', 'Solar Pump Installation'), ('water_treatment', 'Water Treatment'), ('pipeline_extension', 'Pipeline Extension'), ('plumbing', 'Plumbing'), ('water_storage', 'Water Storage'), ('maintenance', 'Maintenance'), ('other', 'Other')], max_length=50)),
                ('service_requirements', models.JSONField(blank=True, default=dict, help_text='Service-specific technical requirements')),
                ('service_name_snapshot', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_services', to='quotations.lead')),
            ],
            options={
                'verbose_name': 'Lead Service',
                'verbose_name_plural': 'Lead Services',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
