# Generated by Django 6.0.7 on 2026-08-22 06:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0014_lead_customer_type_lead_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='address_snapshot',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='company_snapshot',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='customer_name_snapshot',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='email_snapshot',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='parent_quotation',
            field=models.ForeignKey(blank=True, help_text='Parent quotation if this is a revision', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='quotations.quotation'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='phone_snapshot',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('revision_required', 'Revision Required'), ('sent', 'Sent'), ('viewed', 'Viewed'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('revision_requested', 'Revision Requested')], default='draft', max_length=50),
        ),
        migrations.CreateModel(
            name='QuotationService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service', models.CharField(choices=[('borehole_drilling', 'Borehole Drilling'), ('solar_pump_installation', 'Solar Pump Installation'), ('water_treatment', 'Water Treatment'), ('pipeline_extension', 'Pipeline Extension'), ('plumbing', 'Plumbing'), ('water_storage', 'Water Storage'), ('maintenance', 'Maintenance'), ('other', 'Other')], max_length=50)),
                ('service_name_snapshot', models.CharField(blank=True, max_length=255, null=True)),
                ('service_requirements', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_services', to='quotations.quotation')),
            ],
            options={
                'verbose_name': 'Quotation Service',
                'verbose_name_plural': 'Quotation Services',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='quotation_service',
            field=models.ForeignKey(blank=True, help_text='Link to quotation service for organization', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='quotations.quotationservice'),
        ),
    ]
