# Generated by Django 6.0.7 on 2026-08-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0016_quotation_approval_notes_quotation_customer_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='generated_pdf',
            field=models.FileField(blank=True, null=True, upload_to='quotations/pdfs/'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='pdf_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
