# Generated by Django 6.0.7 on 2026-08-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0017_quotation_generated_pdf_quotation_pdf_generated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='service',
            field=models.CharField(blank=True, choices=[('borehole_drilling', 'Borehole Drilling'), ('solar_pump_installation', 'Solar Pump Installation'), ('water_treatment', 'Water Treatment'), ('pipeline_extension', 'Pipeline Extension'), ('plumbing', 'Plumbing'), ('water_storage', 'Water Storage'), ('maintenance', 'Maintenance'), ('water_taps_accessories', 'Water Taps & Accessories'), ('other', 'Other')], help_text='Legacy field - use LeadService for multi-service support', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='leadservice',
            name='service',
            field=models.CharField(choices=[('borehole_drilling', 'Borehole Drilling'), ('solar_pump_installation', 'Solar Pump Installation'), ('water_treatment', 'Water Treatment'), ('pipeline_extension', 'Pipeline Extension'), ('plumbing', 'Plumbing'), ('water_storage', 'Water Storage'), ('maintenance', 'Maintenance'), ('water_taps_accessories', 'Water Taps & Accessories'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='quotationservice',
            name='service',
            field=models.CharField(choices=[('borehole_drilling', 'Borehole Drilling'), ('solar_pump_installation', 'Solar Pump Installation'), ('water_treatment', 'Water Treatment'), ('pipeline_extension', 'Pipeline Extension'), ('plumbing', 'Plumbing'), ('water_storage', 'Water Storage'), ('maintenance', 'Maintenance'), ('water_taps_accessories', 'Water Taps & Accessories'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='quotationtemplate',
            name='service',
            field=models.CharField(choices=[('borehole_drilling', 'Borehole Drilling'), ('solar_pump_installation', 'Solar Pump Installation'), ('water_treatment', 'Water Treatment'), ('pipeline_extension', 'Pipeline Extension'), ('plumbing', 'Plumbing'), ('water_storage', 'Water Storage'), ('maintenance', 'Maintenance'), ('tank_installation', 'Tank Installation'), ('water_taps_accessories', 'Water Taps & Accessories'), ('other', 'Other')], max_length=50),
        ),
    ]
