# Generated by Django 6.0.7 on 2026-08-29 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0018_alter_lead_service_alter_leadservice_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='assigned_to',
        ),
    ]
