# Generated by Django 6.0.7 on 2026-08-31 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0019_remove_lead_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='quotations.lead'),
        ),
    ]
