# Generated by Django 6.0.7 on 2026-09-01 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0020_alter_quotation_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='include_vat',
            field=models.BooleanField(default=True),
        ),
    ]
