# Generated by Django 6.0.7 on 2026-09-01 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0021_quotation_include_vat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationitem',
            name='unit',
            field=models.CharField(choices=[('each', 'Pieces'), ('meter', 'Meter'), ('square_meter', 'Square Meter'), ('cubic_meter', 'Cubic Meter'), ('hour', 'Hour'), ('day', 'Day'), ('kg', 'Kilogram'), ('ton', 'Ton'), ('liter', 'Liter'), ('set', 'Set'), ('none', 'N/A')], max_length=50),
        ),
    ]
