# Generated by Django 6.0.7 on 2026-08-02 10:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True)),
                ('email_leads', models.BooleanField(default=True)),
                ('email_quotations', models.BooleanField(default=True)),
                ('email_projects', models.BooleanField(default=True)),
                ('email_inventory', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('push_leads', models.BooleanField(default=True)),
                ('push_quotations', models.BooleanField(default=True)),
                ('push_projects', models.BooleanField(default=True)),
                ('push_inventory', models.BooleanField(default=True)),
                ('in_app_leads', models.BooleanField(default=True)),
                ('in_app_quotations', models.BooleanField(default=True)),
                ('in_app_projects', models.BooleanField(default=True)),
                ('in_app_inventory', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('lead_new', 'New Lead'), ('lead_assigned', 'Lead Assigned'), ('lead_status', 'Lead Status Change'), ('quotation_created', 'Quotation Created'), ('quotation_submitted', 'Quotation Submitted'), ('quotation_approved', 'Quotation Approved'), ('quotation_sent', 'Quotation Sent'), ('quotation_accepted', 'Quotation Accepted'), ('quotation_rejected', 'Quotation Rejected'), ('quotation_revision', 'Quotation Revision Requested'), ('project_created', 'Project Created'), ('project_updated', 'Project Updated'), ('inventory_low', 'Low Inventory'), ('employee_change', 'Employee Change'), ('system', 'System')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('lead_id', models.UUIDField(blank=True, null=True)),
                ('quotation_id', models.UUIDField(blank=True, null=True)),
                ('project_id', models.UUIDField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'), models.Index(fields=['-created_at'], name='notificatio_created_ae6ed6_idx')],
            },
        ),
    ]
