# Generated by Django 6.0.7 on 2026-08-16 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('lead_new', 'New Lead'), ('lead_assigned', 'Lead Assigned'), ('lead_status', 'Lead Status Change'), ('quotation_created', 'Quotation Created'), ('quotation_submitted', 'Quotation Submitted'), ('quotation_approved', 'Quotation Approved'), ('quotation_sent', 'Quotation Sent'), ('quotation_accepted', 'Quotation Accepted'), ('quotation_rejected', 'Quotation Rejected'), ('quotation_revision', 'Quotation Revision Requested'), ('project_created', 'Project Created'), ('project_updated', 'Project Updated'), ('inventory_low', 'Low Inventory'), ('employee_change', 'Employee Change'), ('employee_allocation_review', 'Employee Allocation Review'), ('system', 'System')], max_length=50),
        ),
    ]
