# Generated by Django 5.0.8 on 2026-07-26 22:23

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('projects', '0001_initial'),
        ('users', '0005_invitation_permissions_userprofile_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_projects', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_reference',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='ProjectActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_name', models.CharField(default='New Activity', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('progress', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold')], default='in_progress', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='projects.project')),
            ],
            options={
                'verbose_name': 'Project Activity',
                'verbose_name_plural': 'Project Activities',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ActivityUpdateHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('status_changed', 'Status Changed'), ('progress_changed', 'Progress Changed'), ('resource_changed', 'Resources Changed')], max_length=30)),
                ('before_value', models.TextField(blank=True, null=True)),
                ('after_value', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_updates', to='users.userprofile')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_history', to='projects.projectactivity')),
            ],
            options={
                'verbose_name': 'Activity Update History',
                'verbose_name_plural': 'Activity Update Histories',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='activity_images/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.projectactivity')),
            ],
            options={
                'verbose_name': 'Activity Image',
                'verbose_name_plural': 'Activity Images',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectFieldHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_changes', to='users.userprofile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_history', to='projects.project')),
            ],
            options={
                'verbose_name': 'Project Field History',
                'verbose_name_plural': 'Project Field Histories',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectResourceAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resource_type', models.CharField(choices=[('company_tool', 'Company Tool'), ('money', 'Money')], max_length=20)),
                ('tool_name', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('allocated_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('money_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('money_purpose', models.CharField(blank=True, max_length=255)),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('allocated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_allocations', to='projects.project')),
            ],
            options={
                'verbose_name': 'Project Resource Allocation',
                'verbose_name_plural': 'Project Resource Allocations',
                'ordering': ['resource_type', 'tool_name'],
            },
        ),
        migrations.CreateModel(
            name='ActivityResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resource_type', models.CharField(choices=[('company_tool', 'Company Tool'), ('hired_tool', 'Hired Tool'), ('money', 'Money')], max_length=20)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('hired_tool_name', models.CharField(blank=True, max_length=255)),
                ('hired_from', models.CharField(blank=True, max_length=255)),
                ('hired_tool_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('money_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('money_purpose', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventoryitem')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='projects.projectactivity')),
                ('project_allocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_draws', to='projects.projectresourceallocation')),
            ],
            options={
                'verbose_name': 'Activity Resource',
                'verbose_name_plural': 'Activity Resources',
            },
        ),
    ]
