# Generated by Django 5.0.8 on 2026-07-28 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_archived_at_project_archived_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectresourceallocation',
            name='hired_from',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectresourceallocation',
            name='hired_tool_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='projectresourceallocation',
            name='resource_type',
            field=models.CharField(choices=[('company_tool', 'Company Tool'), ('hired_tool', 'Hired Tool'), ('money', 'Money')], max_length=20),
        ),
    ]
