# Generated by Django 5.0.8 on 2026-07-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectresourceallocation_hired_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectresourceallocation',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectresourceallocation',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
